<?php

/**
 * Implements hook_block_info().
 */
function pp_gmaps_block_info() {

  $blocks['gmaps'] = array(
    'info' => t('GMaps Block for homepage'),
    'region' => 'content',
    'status' => TRUE,
    'cache' => DRUPAL_NO_CACHE
  );

  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function pp_gmaps_block_view($delta = '') {
  // This example is adapted from node.module.
  $block = array();

  switch ($delta) {
    case 'gmaps':
      $block['subject'] = t('GMaps Block');
      $block['content'] = array(
        '#theme' => 'homepage_gmaps',
        '#url' => 'rss.xml',
        '#title' => t('Syndicate'),
      );
      break;
  }
  return $block;
}

function pp_gmaps_theme($existing, $type, $theme, $path) {
  return array(
    'homepage_gmaps' => array(
      'template' => 'templates/pp_gmaps',
      'variables' => array(
        'var_name'=> NULL
      )
    ),
  );
}


/**
 * Implements hook_preprocess_HOOK().
 */
function pp_gmaps_preprocess_page(&$variables) {
  drupal_add_js('https://maps.googleapis.com/maps/api/js?key=AIzaSyCxPMFKItqPYezCGKYcvFl3reOl70tO1jM', 'external');
  drupal_add_js(drupal_get_path('module', 'pp_gmaps') . '/js/pp_gmaps.js', 'file');
}